#!/bin/sh
sleep 1
./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET & ./SKYNET &
btop
